version: "3.9"
services:
  mysql_db:
    image: mysql:5.7
    container_name: premium-mysql1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: riskcovry_test
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    ports:
      - "33010:3306"
    volumes:
      - ./tmp/mysql_db:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    environment:
      HOST: mysql_db